import React from "react";

function Copenhagen() {
    return(
        <div className="contentContainer">
            <p>Copenhagen (Danish: København [købm̩ˈhɑwˀn]) is the capital and most populous city of Denmark. As of July 2018, the city has a population of 777,218 (616,098 in Copenhagen Municipality, 103,914 in Frederiksberg Municipality, 43,005 in Tårnby Municipality, and 14,201 in Dragør Municipality).[3][7][8] It forms the core of the wider urban area of Copenhagen (population 1,627,705) and the Copenhagen metropolitan area (population 2,057,737). Copenhagen is situated on the eastern coast of the island of Zealand; another small portion of the city is located on Amager, and is separated from Malmö, Sweden, by the strait of Øresund. The Øresund Bridge connects the two cities by rail and road.</p>
            <p>Originally a Viking fishing village established in the 10th century in the vicinity of what is now Gammel Strand, Copenhagen became the capital of Denmark in the early 15th century. Beginning in the 17th century it consolidated its position as a regional centre of power with its institutions, defences and armed forces. After suffering from the effects of plague and fire in the 18th century, the city underwent a period of redevelopment. This included construction of the prestigious district of Frederiksstaden and founding of such cultural institutions as the Royal Theatre and the Royal Academy of Fine Arts. After further disasters in the early 19th century when Horatio Nelson attacked the Dano-Norwegian fleet and bombarded the city, rebuilding during the Danish Golden Age brought a Neoclassical look to Copenhagen's architecture. Later, following the Second World War, the Finger Plan fostered the development of housing and businesses along the five urban railway routes stretching out from the city centre.</p>
            <p>Since the turn of the 21st century, Copenhagen has seen strong urban and cultural development, facilitated by investment in its institutions and infrastructure. The city is the cultural, economic and governmental centre of Denmark; it is one of the major financial centres of Northern Europe with the Copenhagen Stock Exchange. Copenhagen's economy has seen rapid developments in the service sector, especially through initiatives in information technology, pharmaceuticals and clean technology. Since the completion of the Øresund Bridge, Copenhagen has become increasingly integrated with the Swedish province of Scania and its largest city, Malmö, forming the Øresund Region. With a number of bridges connecting the various districts, the cityscape is characterised by parks, promenades and waterfronts. Copenhagen's landmarks such as Tivoli Gardens, The Little Mermaid statue, the Amalienborg and Christiansborg palaces, Rosenborg Castle Gardens, Frederik's Church, and many museums, restaurants and nightclubs are significant tourist attractions. The largest lake of Denmark, Arresø, lies around 27 miles (43 kilometers) northwest of the City Hall Square.</p>
            <p>Copenhagen is home to the University of Copenhagen, the Technical University of Denmark, Copenhagen Business School and the IT University of Copenhagen. The University of Copenhagen, founded in 1479, is the oldest university in Denmark. Copenhagen is home to the FC København and Brøndby football clubs. The annual Copenhagen Marathon was established in 1980. Copenhagen is one of the most bicycle-friendly cities in the world.</p>
            <p>The Copenhagen Metro launched in 2002 serves central Copenhagen while the Copenhagen S-train, the Lokaltog (private railway) and the Coast Line network serves and connects central Copenhagen to outlying boroughs. To relieve traffic congestion, the Fehmarn Belt Fixed Link road and rail construction is planned, because the narrow 9-9.5 mile isthmus between Roskilde Fjord and Køge Bugt (Køge Bay) forms a traffic bottleneck. The Copenhagen-Ringsted Line will relieve traffic congestion in the corridor between Roskilde and Copenhagen.</p>
            <p>Serving roughly two million passengers a month, Copenhagen Airport, Kastrup, is the busiest airport in the Nordic countries.</p>
        </div>
    )
}

export default Copenhagen;