import React from "react";
import Source from "./Source";

function Seine() {
    return(
        <div className="contentContainer">
            <h5>Outstanding Universal Value</h5>
            <p><strong>Brief synthesis</strong></p>
            <p>The city of Paris is built along a bend in the River Seine, between the confluence of the Marne and the Oise Rivers. The property comprises bridges, quays and the banks of the Seine in the historic part of its course (between the Pont de Sully and the Pont d’Iéna) and the Ile de la Cité and the Ile St Louis. The mastery of the architecture and town planning along the river is evident in the articulation of the Ile de la Cité and Ile St Louis with its banks, the creation of North-South thoroughfares, the installations along the river course, the construction of quays and the channelling of the river. The ensemble, regarded as a geographical and historical entity, forms an exceptional and unique example of urban riverside architecture, where the different layers of the history of Paris, the capital city of one of the first great nation states of Europe, are harmoniously superposed.</p>
            <p>From the Ile St Louis to the Pont Neuf, from the Louvre to the Eiffel Tower, and the Place de la Concorde to the Grand and Petit Palais, the evolution of Paris and its history can be seen from the River Seine. A large number of major monuments of the French capital are built alongside the river and on the perspectives overlooking it. The Cathedral of Notre-Dame and the Sainte Chapelle are architectural masterpieces of the Middle Ages; the Pont Neuf illustrates the spirit of French Renaissance; the coherence of the districts of the Marais and the Ile-Saint-Louis testify to Parisian town planning of the 17th and 18th centuries; finally, the banks of the river comprise the most masterful constructions of French classicism, with the Palais de Louvre, the Invalides, the Ecole Militaire and the Monnaie (the Mint). The conserved buildings of the Universal Exhibitions that took place in Paris in the 19th and 20th centuries are numerous on the banks of the River Seine. Heading the list is the Eiffel Tower, a universally recognized icon of Paris and of iron architecture. The Ile Saint Louis, the Quai Malaquais and the Quai Voltaire offer examples of coherent architectural and urban ensembles, with very significant examples of Parisian construction of the 17th and 18th centuries. The large squares and avenues built by Haussmann at the time of Napoleon&nbsp;III have influenced town planning throughout the world.</p>
            <p><strong>Criterion (i)</strong><strong>&nbsp;</strong><strong>: </strong>The banks of the Seine are studded with a succession of architectural and urban masterpieces built from the Middle Ages to the 20th century, including the Cathedral of Notre-Dame and the Sainte Chapelle, the Louvre, the Palais de l’Institut, the Hôtel des Invalides, Place de la Concorde, Ecole Militaire, the Monnaie (the Mint), the Grand Palais of the Champs Elysées, the Eiffel Tower and the Palais de Chaillot.</p>
            <p><strong>Criterion (ii)</strong><strong>&nbsp;</strong><strong>: </strong>Buildings along the Seine, such as Notre-Dame and the Sainte Chapelle, became the source of the spread of Gothic architecture, while the Place de la Concorde and the vista at the Invalides exerted influence on urban development of European capitals. Haussmann’s urban planning, which marks the western part of the city, inspired the construction of the great cities of the New World, in particular in Latin America. Finally, the Eiffel Tower and the Grand and Petit Palais, the Pont Alexandre&nbsp;III and the Palais de Chaillot are the living testimony of the universal exhibitions, which were of such great importance in the 19th and 20th centuries.</p>
            <p><strong>Criterion (iv)</strong><strong>&nbsp;</strong><strong>: </strong>United by a grandiose river landscape, the monuments, the architecture and the representative buildings along the banks of the Seine in Paris each illustrate with perfection, most of the styles, decorative arts and building methods employed over nearly eight centuries.</p>
            <p><strong>Integrity</strong></p>
            <p>Paris is a river city. Ever since the first human settlements, from prehistoric times to the Parisii tribes, the Seine has played both a defensive and an economic role. The present historic city, which developed between the 16th and 20th centuries, expresses the evolution of the relationship between the river and the city. The well-defined area between the Pont de Sully and the Pont d’Iéna is based on the age-old distinction between upstream and downstream. Upstream, the port and river transport; downstream, royal and aristocratic Paris. It is this latter section of the Seine, where functions of the capital city have developed, that was inscribed. The presence of the State through its achievements and legislation has enabled the preservation of the property in its entire integrity.</p>
            <p><strong>Authenticity</strong></p>
            <p>The completion and consolidation of the riverside, urban and monumental vistas of Paris date from the first half of the 20th century, with the Palais de Tokyo and the Palais de Chaillot. The urban and visual integrity of the site (wide perspectives from the banks) is vulnerable to the pressures of urban development, traffic pollution and tourism, and requires a rigorous control to maintain intact its Outstanding Universal Value.</p>
            <p><strong>Protection and management requirements</strong></p>
            <p>The ensemble of the property enjoys the highest level of legal protection (Heritage Code, Town Planning Code, Environment Code). The property is in an inscribed site, and further comprises six listed sites, notably the Invalides, as well as the Champs de Mars and the Jardins de Trocadéro. Regarding the Historic Monuments, all the important monuments are fully listed.</p>
            <p>The State owns, directly or through its public establishments, the quays of the Seine (fluvial public domain), the majority of the monuments and their associated spaces. The city of Paris owns the public areas, the Hôtel de Ville, the parish churches and numerous other plots of land and buildings.</p>
            <p>There is no management plan or management authority specifically devoted to the World Heritage property. However, due to the legal and regutory protection, management by the owner or tenants is scientifically and technically controlled by the State.&nbsp;</p>
            <p>The “Cahier des prescriptions urbaines et paysagères pour la mise en valeur des Berges de la Seine dans Paris” (Urban and Landscape Requirements for the Enhancement of the Banks of the Seine in Paris), prepared in 1999 by the city, the State and the autonomous Port, is the reference document for all activity and installations on the banks. The “Specifications de prescription des installations saisonnières” (Seasonal Installation Requirements), approved in 2015, aims to control the temporary use and occupation of the thoroughfares of the lower quays of the banks of the Seine in Paris. The definitive closing of the lower quays to automobile traffic over nearly the whole area of the property, since 2014 on the Left Bank and 2016 on the Right Bank, as part of the development of the banks of the Seine, contributes to preserving its authenticity and integrity.</p>
            <Source text="https://whc.unesco.org/en/list/600" />
        </div>
    )
}

export default Seine;